// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using skipper_api.Data;

#nullable disable

namespace skipper_api.Data.Migrations
{
    [DbContext(typeof(ProfessorDbContext))]
    [Migration("20260801193455_AddEnclosureTimeline")]
    partial class AddEnclosureTimeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("skipper_api.Domain.Animals.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AcquiredDate")
                        .HasColumnType("date");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<bool>("BirthDateIsEstimated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DispositionDate")
                        .HasColumnType("date");

                    b.Property<string>("DispositionReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("MicrochipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubspeciesOrMorph")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TagIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalType")
                        .HasDatabaseName("IX_Animals_AnimalType");

                    b.HasIndex("EnclosureId")
                        .HasDatabaseName("IX_Animals_EnclosureId");

                    b.HasIndex("MicrochipNumber")
                        .HasDatabaseName("IX_Animals_MicrochipNumber");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Animals_Name");

                    b.HasIndex("Species")
                        .HasDatabaseName("IX_Animals_Species");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Animals_Status");

                    b.HasIndex("TagIdentifier")
                        .HasDatabaseName("IX_Animals_TagIdentifier");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("skipper_api.Domain.EnclosureTimeline.EnclosureTimelineEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SourceReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId")
                        .HasDatabaseName("IX_EnclosureTimelineEvents_EnclosureId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_EnclosureTimelineEvents_EventType");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_EnclosureTimelineEvents_OccurredAt");

                    b.HasIndex("EnclosureId", "OccurredAt")
                        .HasDatabaseName("IX_EnclosureTimelineEvents_EnclosureId_OccurredAt");

                    b.ToTable("EnclosureTimelineEvents", (string)null);
                });

            modelBuilder.Entity("skipper_api.Domain.Enclosures.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DimensionUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Height")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("Length")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaxAnimalCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Mobility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SafetyRating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SizeLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("VolumeUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Width")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Location")
                        .HasDatabaseName("IX_Enclosures_Location");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Enclosures_Name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Enclosures_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Enclosures_Type");

                    b.ToTable("Enclosures", (string)null);
                });

            modelBuilder.Entity("skipper_api.Domain.Animals.Animal", b =>
                {
                    b.HasOne("skipper_api.Domain.Enclosures.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("skipper_api.Domain.EnclosureTimeline.EnclosureTimelineEvent", b =>
                {
                    b.HasOne("skipper_api.Domain.Enclosures.Enclosure", "Enclosure")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("skipper_api.Domain.Enclosures.Enclosure", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("TimelineEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
